site_name: Wire Harnessing Docs
theme:
  name: material
  palette:
  - scheme: slate
    primary: blue
nav:
- Daybreak:
  - MPPT Enclosure: Daybreak/MPPT Enclosure/index.md
  - Motor Controller Enclosure: Daybreak/Motor Controller Enclosure/index.md
  - Supplemental Battery Enclosure: Daybreak/Supplemental Battery Enclosure/index.md
markdown_extensions:
- attr_list
