name: Build and Deploy MkDocs

on:
  push:
    branches:
      - gh-pages-src
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages-src
        uses: actions/checkout@v4

      # 0️⃣ Skip workflow if commit was from GitHub Actions bot
      - name: Skip if triggered by GitHub Actions
        run: |
          AUTHOR=$(git log -1 --pretty=format:'%an')
          echo "Last commit author: $AUTHOR"
          if [ "$AUTHOR" = "github-actions[bot]" ]; then
            echo "Commit was from GitHub Actions, exiting workflow."
            exit 0
          fi
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build and deploy site
        run: mkdocs gh-deploy --force --clean