name: Deploy Assets

on:
  push:
    branches:
      - main
      - gh-pages-src
  workflow_dispatch:

jobs:
  deploy-and-generate:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the branch that triggered the workflow
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Set CURRENT_BRANCH environment variable
      - name: Determine current branch
        id: vars
        run: echo "CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      # 3️⃣ If not main, checkout main to get latest assets
      - name: Checkout main if needed
        run: |
          if [ "$CURRENT_BRANCH" != "main" ]; then
            git fetch origin main:main
            git checkout main
          fi

      # 4️⃣ Prepare _temp folder
      - name: Prepare _temp folder
        run: |
          rm -rf _temp
          mkdir -p _temp

      # 5️⃣ Copy subdirectories (ignore hidden files/folders)
      - name: Copy subdirectories to _temp
        run: |
          shopt -s dotglob
          for item in */ ; do
            [[ "$item" == .* ]] && continue
            rsync -av --exclude='.*' "$item" _temp/
          done

      # 6️⃣ Checkout gh-pages-src branch (create if it doesn't exist)
      - name: Checkout gh-pages-src
        run: |
          git fetch origin gh-pages-src:gh-pages-src || git checkout --orphan gh-pages-src
          git checkout gh-pages-src

      # 7️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # 8️⃣ Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 9️⃣ Run gen_docs.py
      - name: Generate MkDocs docs
        run: python gen_docs.py

      # 🔟 Delete _temp folder
      - name: Clean up _temp folder
        run: rm -rf _temp

      # 1️⃣1️⃣ Commit and push changes to gh-pages-src
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs mkdocs.yml
          git commit -m "Update projects and regenerate docs" || echo "No changes to commit"
          git push origin gh-pages-src

      # 1️⃣2️⃣ Build and deploy MkDocs to gh-pages
      - name: Build and deploy site
        run: mkdocs gh-deploy --force --clean
