name: Deploy Assets

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-assets:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Prepare gh-pages-src branch
      - name: Checkout gh-pages-src branch
        run: |
          git fetch origin gh-pages-src:gh-pages-src || git checkout --orphan gh-pages-src
          git checkout gh-pages-src

      # 3️⃣ Remove old projects folder
      - name: Clear old projects
        run: |
          rm -rf projects
          mkdir -p projects

      # 4️⃣ Copy all subdirectories from main into gh-pages-src/projects
      - name: Copy assets
        run: |
          shopt -s dotglob
          for item in */ ; do
            # Skip hidden folders/files
            [[ "$item" == .* ]] && continue
            rsync -av --exclude='.*' "$item" projects/
          done

      # 5️⃣ Commit & push changes
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add projects
          git commit -m "Update projects from main" || echo "No changes to commit"
          git push origin gh-pages-src
